- hosts: all
  become: true
  tasks:
    - name: Stop and remove old container (if running)
      community.docker.docker_container:
        name: webapp
        state: absent

    - name: Run container from image
      community.docker.docker_container:
        name: webapp
        image: local/webapp:v1
        state: started
        published_ports:
          - "80:80"

