---
- name: Deploy Docker Container on Remote Server
  hosts: webserver
  become: true
  tasks:
    - name: Load Docker image
      copy:
        src: /tmp/app_image.tar
        dest: /tmp/app_image.tar

    - name: Load image into Docker
      command: docker load -i /tmp/app_image.tar

    - name: Stop and remove old container (if running)
      docker_container:
        name: webapp
        state: absent
        force_kill: yes

    - name: Run new container
      docker_container:
        name: webapp
        image: local/app:v1
        state: started
        ports:
          - "80:80"

